### ISSUE TITLE
iptables' state module is obsolete

### ISSUE THREAD

**Issue by jeka** [drsound/fault_tolerant_router#1]
While technically it will work (still), considering the fact that this is freshly released project I would suggest you to replace usage of iptables **state** module with **conntrack** module.
The **state** module is considered obsolete and **conntrack** is its (more powerful) replacement

**Comment by drsound** [comment]
You're right! As it's written in the README, the program was developed and internally used since several years, **state** module is a legacy from that time. I will care about it in a short time.

**Comment by drsound** [comment]
jeka, thanks again for your suggestion! :-)
