### ISSUE TITLE
Support for dynamic IP uplinks without NAT (for example USB 3G dongles)

### ISSUE THREAD

**Issue by drsound** [drsound/fault_tolerant_router#12]
Fault Tolerant Router is already working fine with dynamic IP uplinks, if they provide NAT (for example DSL routers). The problem is with dynamic IP uplinks that assign such dynamic IP directly on Linux interface, for example USB 3G dongles using PPP interfaces. See issue #11.

**Comment by kilmarnock** [comment]
Please implement this feature. I want to say that also DSL connections (PPPoE) require dynamic interfaces, like usb tethering does. The solution is not to give all connection parameters twice but to read them from the system.

**Comment by drsound** [comment]
PPP dynamic IP support is now in development branch, some testing is appreciated.

**Comment by drsound** [comment]
PPP dynamic IP support is now in master branch and a new gem (v1.1.0) is out. Please test is possible, because I have no real PPP uplink, so I could't do it extensively.

**Comment by drsound** [comment]
PPP dynamic IP support is now in master branch and a new gem (v1.1.0) is out. Please test is possible, because I have no real PPP uplink, so I could't do it extensively.
