### ISSUE TITLE
Description on how to specify dynamic interfaces?

### ISSUE THREAD

**Issue by rubin110** [drsound/fault_tolerant_router#13]
I have 2 uplinks, one is DSL with a static IP address, and the other is a roof top wireless ISP that spits out dynamic addresses. I don't see any instructions in the readme nor in the config file on how to specify that a particular interface is dynamically set. Am I missing where to find these instructions? Thanks!

**Comment by rubin110** [comment]
Ok I feel silly, it seems like the previous bug to this one...

https://github.com/drsound/fault_tolerant_router/issues/12

Is specifically asking for dynamic IP address support, as in this particular use case. Closing out this ticket.

**Comment by drsound** [comment]
Yes, you're right. Try to see if my proposed solution for issue #11 works for you, as a temporary solution. I will implement dynamic IP support as next step, so stay tuned.

**Comment by rubin110** [comment]
Due to my inability to get inability to get this running (and a large number of other factors, like how AT&T is screwing my house over from getting better DSL from another more friendly local provider), I've gotten rid of an uplink and am down to 1 connection currently going into my home. I'll revisit this project again once I've setup another roof top AP pointed to a friend's house down the block. Thanks!

**Comment by drsound** [comment]
PPP dynamic IP support is now in master branch and a new gem (v1.1.0) is out. Please test is possible, because I have no real PPP uplink, so I could't do it extensively.
