### ISSUE TITLE
Handle PPP interfaces with no IP address

### ISSUE THREAD

**Issue by drsound** [drsound/fault_tolerant_router#16]
Avoid using and testing a PPP interface if it has no IP address (for examle because it is in handshake phase or the DSL is down).

**Comment by saikumar25** [comment]
Hi,

Sorry didnt check my mail , thanks for the upgrade to support ppp interfaces as well . Well , in my test scenario I kept WAN 1 as ethernet interface and WAN 2 as ppp 

I generated /etc//fault_tolerant_router.conf and when I was trying to generate iptables for it by saying
fault_tolerant_router generate_iptables

I am getting an error saying : 
/var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplink.rb:48:in `detect_ppp_ips!': undefined method`getifaddrs' for Socket:Class (NoMethodError)
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplink.rb:36:in `initialize'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in`new'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in `block in initialize'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in`each'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in `each_with_index'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in`each'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in `map'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/lib/fault_tolerant_router/uplinks.rb:4:in`initialize'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/bin/fault_tolerant_router:90:in `new'
    from /var/lib/gems/1.9.1/gems/fault_tolerant_router-1.1.0/bin/fault_tolerant_router:90:in`<top (required)>'
    from /usr/local/bin/fault_tolerant_router:23:in `load'
    from /usr/local/bin/fault_tolerant_router:23:in`<main>'

**Comment by drsound** [comment]
Please try the just released 1.2.0 version and let me know if your problem is solved.

**Comment by saikumar25** [comment]
OK thanks.
