### ISSUE TITLE
with static its, gives RTNETLINK error

### ISSUE THREAD

**Issue by blackbadgerltd** [drsound/fault_tolerant_router#21]
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such process
RTNETLINK answers: No such process
RTNETLINK answers: No such process
RTNETLINK answers: No such process
RTNETLINK answers: No such process
RTNETLINK answers: No such process

with cons file:

uplinks:
- interface: eth1
  type: static
  ip: 192.168.1.17
  gateway: 192.168.1.1
  description: Example Provider 1
  priority_group: 1
  #optional parameter
  weight: 1
- interface: eth3
  type: static
  ip: 192.168.1.22
  gateway: 192.168.1.1
  description: Example Provider 2
  priority_group: 1
  #optional parameter
  weight: 2

downlinks:
  lan: wlan0
  #leave blank if you have no DMZ
  dmz:

tests:
  #an array of IP addresses to ping to verify the uplinks state. You can add as
  #many as you wish. Predefined ones are Google DNS, OpenDNS DNS, other public
  #DNS. Every time an uplink is tested the IP addresses are shuffled, so listing
  #order is not important.
  ips:
- 8.8.8.8
- 8.8.4.4
- 208.67.222.222
- 208.67.220.220
- 4.2.2.2
- 4.2.2.3
  #number of successfully pinged IP addresses to consider an uplink to be
  #functional
  required_successful: 4
  #number of ping retries before giving up on an IP
  ping_retries: 1
  #seconds between a check of the uplinks and the next one
  interval: 30

log:
  #file: "/var/log/fault_tolerant_router.log"
  file: "/tmp/fault_tolerant_router.log"
  #maximum log file size (in bytes). Once reached this size, the log file will
  #be rotated.
  max_size: 1024000
  #number of old rotated files to keep
  old_files: 10

email:
  send: false
  sender: router@domain.com
  recipients:
- user1@domain.com
- user2@domain.com
- user3@domain.com
  #see http://ruby-doc.org/stdlib-2.3.1/libdoc/net/smtp/rdoc/Net/SMTP.html
  smtp_parameters:
    address: smtp.gmail.com
    port: 587
    #domain: domain.com
    authentication: :login
    enable_starttls_auto: true
    user_name: user@gmail.com
    password: secret-password
# base IP route table number, just need to change if you are already using
# multiple routing tables

base_table: 1
# just need to change if you are already using ip policy routing, to avoid
# overlapping, must be higher than 32767 (the default routing table priority,
# see output of "ip rule" command)

base_priority: 40000
# just need to change if you are already using packet marking, to avoid
# overlapping

base_fwmark: 1

**Comment by drsound** [comment]
Don't know where those _RTNETLINK answers_, but there is a basic problem here: you have two uplinks in the same IP address class (192.168.1.0/24... I suppose the mask is 24) with the same default route IP address (192.168.1.1)! Try changing the IP address class of one of your uplinks and try again.
